# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# find_suitable_land_with_parameters.py
# Created on: 2021-03-30 03:52:49.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: find_suitable_land_with_parameters <Cities> <Roads_buffer_distance> <Roads> <Cities_buffer_distance> <v_Boundaries> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Cities = arcpy.GetParameterAsText(0)

Roads_buffer_distance = arcpy.GetParameterAsText(1)
if Roads_buffer_distance == '#' or not Roads_buffer_distance:
    Roads_buffer_distance = "10 Miles" # provide a default value if unspecified

Roads = arcpy.GetParameterAsText(2)

Cities_buffer_distance = arcpy.GetParameterAsText(3)
if Cities_buffer_distance == '#' or not Cities_buffer_distance:
    Cities_buffer_distance = "10 Miles" # provide a default value if unspecified

v_Boundaries = arcpy.GetParameterAsText(4)

# Local variables:
Buffer_cities = "D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\us_cities_Buffer"
Buffer_roads = "D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\s_roads_Buffer"
Intersected_buffers = "D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\us_cities_Buffer_Intersect"
Suitable_land = "D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\suitable_land"

# Process: Buffer the cities
arcpy.Buffer_analysis(Cities, Buffer_cities, Cities_buffer_distance, "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Buffer the roads
arcpy.Buffer_analysis(Roads, Buffer_roads, Roads_buffer_distance, "FULL", "FLAT", "ALL", "", "PLANAR")

# Process: Intersect
arcpy.Intersect_analysis("D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\us_cities_Buffer #;D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\s_roads_Buffer #", Intersected_buffers, "ALL", "", "INPUT")

# Process: Clip
arcpy.Clip_analysis(Intersected_buffers, v_Boundaries, Suitable_land, "")

