# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# find_suitable_land.py
# Created on: 2021-03-30 03:46:28.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
US_Cities = "D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\us_cities"
Buffer_cities = "D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\us_cities_Buffer"
US_Roads = "D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\us_roads"
Buffer_roads = "D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\s_roads_Buffer"
Intersected_buffers = "D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\us_cities_Buffer_Intersect"
US_Boundaries = "D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\us_boundaries"
Suitable_land = "D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\suitable_land"

# Process: Buffer the cities
arcpy.Buffer_analysis(US_Cities, Buffer_cities, "10 Miles", "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Buffer the roads
arcpy.Buffer_analysis(US_Roads, Buffer_roads, "10 Miles", "FULL", "FLAT", "ALL", "", "PLANAR")

# Process: Intersect
arcpy.Intersect_analysis("D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\us_cities_Buffer #;D:\\MY\\KNU\\3_COURSE\\2_Semertr\\Programing_GIS\\My_work\\Arcpy\\Programming_in_GIS_2021_L5_materials\\USA.gdb\\s_roads_Buffer #", Intersected_buffers, "ALL", "", "INPUT")

# Process: Clip
arcpy.Clip_analysis(Intersected_buffers, US_Boundaries, Suitable_land, "")

